# Dynamics model parameters for NEXXUS_ROV

NEXXUS_ROV/num_actuators: 5
NEXXUS_ROV/dynamics/period: 0.001
NEXXUS_ROV/dynamics/uwsim_period: 0.001
NEXXUS_ROV/dynamics/mass: 100
NEXXUS_ROV/dynamics/gravity_center: [0.0, 0.0, 0.2]
NEXXUS_ROV/dynamics/g: -0.1
NEXXUS_ROV/dynamics/radius: 2

NEXXUS_ROV/dynamics/ctf: 0.00006835
NEXXUS_ROV/dynamics/ctb: 0.00006835

#Actuator tau for first order actuator dynamic model
NEXXUS_ROV/dynamics/actuators_tau: [0.2, 0.2, 0.2, 0.2,0.2]
#Inputs higher than actuators_maxsat will saturate to actuators_maxsat
NEXXUS_ROV/dynamics/actuators_maxsat: [10, 10, 10, 10, 10]
#Inputs below actuators_minsat will saturate to actuators_minsat
NEXXUS_ROV/dynamics/actuators_minsat: [-10, -10, -10, -10, -10]
#Inputs to actuators will be scaled to actuators_gain,
NEXXUS_ROV/dynamics/actuators_gain: [1000, 1000, 1000, 1000, 1000]

NEXXUS_ROV/dynamics/dzv: 0.05
NEXXUS_ROV/dynamics/dv: 0.35
NEXXUS_ROV/dynamics/dh: 0.4
NEXXUS_ROV/dynamics/density: 1000.0

NEXXUS_ROV/dynamics/tensor: [8.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 8.0]
NEXXUS_ROV/dynamics/damping: [.0, .0, .0, -130.0, -130.0, -130.0]
NEXXUS_ROV/dynamics/quadratic_damping: [-148.0, -148.0, -148.0, -180.0, -180.0, -180.0]

NEXXUS_ROV/dynamics/Mrb: [ 98.0,    0.0,    0.0,    0.0,    4.9,  -0.0,
                     0.0,   98.0,    0.0,   -4.9,   0.0,    0.0,
                     0.0,    0.0,   98.0,    0.0,   -0.0,    0.0,
                     0.0,   -4.9,   0.0,    8.0,    0.0,    0.0,
                     4.9,   0.0,   -0.0,    0.0,    8.0,    0.0,
                     -0.0,    0.0,    0.0,    0.0,    0.0,    8.0 ]

NEXXUS_ROV/dynamics/Ma: [  49.0,    0.0,    0.0,    0.0,    0.0,   0.0,
                     0.0,    49.0,    0.0,    0.0,    0.0,   0.0,
                     0.0,    0.0,    49.0,    0.0,    0.0,   0.0,
                     0.0,    0.0,    0.0,    0.0,    0.0,   0.0,
                     0.0,    0.0,    0.0,    0.0,    0.0,   0.0,
                     0.0,    0.0,    0.0,    0.0,    0.0,   0.0 ]

#NEXXUS_ROV thrusters.
#Expresion evaluated at each iteration by the python interpreter
#ct is a vector internally defined such that if u[i]>0 then ct[i]=ctf, else ct[i]=ctb, i>=0 and i<number_of_actuators
#du is the vector with the control inputs
#The rest of parameters defined in this file can be referenced here as "self.param", i.e /dynamics/dh maps to "self.dh"
NEXXUS_ROV/dynamics/allocation_matrix: "
[-ct[0]*abs(du[0]),            -ct[1]*abs(du[1]),              .0,                       .0,                           .0,
.0,                             .0,                             .0,                       .0,                           ct[4]*abs(du[4]),
.0,                             .0,                             -ct[2]*abs(du[2]),          -ct[3]*abs(du[3]),            .0,
.0,                             .0,                             .0,                       .0,                           .0,
.0,                             .0,                             -ct[2]*self.dv*abs(du[2]), ct[3]*self.dv*abs(du[3]),     .0,
-ct[0]*self.dh*abs(du[0]),      ct[1]*self.dh*abs(du[1]),       .0,                       .0,                           .0]"

#Meters and Rads [X, Y, Z, Roll, Pitch, Yaw]
NEXXUS_ROV/dynamics/initial_pose: [0, 0, 0, 3.14, 0, 1.27] #[3.0, 1.1, 2.8, 0, 0, 3.14]
NEXXUS_ROV/dynamics/initial_velocity: [0, 0, 0, 0, 0, 0]

NEXXUS_ROV/dynamics/topic_name: "/dataNavigator"
NEXXUS_ROV/dynamics/external_force_topic: "/NEXXUS_ROV/ForceSensor"
NEXXUS_ROV/dynamics/frame_id: "NEXXUS_ROV_base_link"


#WATER CURRENTs SIMULATION
dynamics/current_mean: [1.0, 1., 1.]
dynamics/current_sigma: [0.002, 0.001, 0.001]
dynamics/current_min: [150, 100, 150]
dynamics/current_max: [200., 200., 200.]
